services:
  db:
    image: mariadb
    network_mode: "host"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: crv_clients
  migration:
    build:
      dockerfile: ./Dockerfile.DB
    network_mode: "host"
    depends_on:
      - db
  api:
    build: .
    network_mode: "host"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - PORT=8080
      - DB=root:root@tcp(localhost:3306)
